### ISSUE TITLE
Implement VPN access to the testing enclaves

### ISSUE THREAD

**Issue by justinforbes** [cisagov/cool-system#112]
# 🚀 Feature Proposal

Deploy a remotely accessible VPN in each RVA assessment enclave.

## Motivation

This will enable RVA teams to continue conducting assessments as they are done currently from their assessment laptops.  This will also support the RAP program and allow remote devices to connect to the COOL from customer networks to facilitate remote testing.

**Comment by justinforbes** [comment]
This is MVP for RVAs

**Comment by jasonhillva** [comment]
Discussed w/ Mark, Aastha, and Justin.  Next steps are to receive issues from Justin Forbes on why we need access to the enclave.  Currently NO contractors will be granted access directly into the environment, they will go through the path set by the DEV team.  Assessments and DEV are trying to identify work arounds to the issue.

**Comment by felddy** [comment]
Given @jasonhillva's last comment we're going to look for alternative solutions that will afford the assessors the flexibility and customization they crave.  @justinforbes the dev team has an idea on how to do this.  We should get together and have a discussion w/ 🍻.  

@essex09 would you please [open a separate issue](https://github.com/cisagov/cool-system/issues/new/choose) for the RAP VPN? I know you are using [Wireguard](https://www.wireguard.com/) currently.  We're not against that, but an IPSEC tunnel might make more sense for a machine-to-VPC connection since that can be an AWS-managed service.

**Comment by justinforbes** [comment]
That sounds good to me just let me know when works for you?
