### ISSUE TITLE
COOL VPN Down

### ISSUE THREAD

**Issue by brubach** [cisagov/cool-system#150]
# 🐛 Summary #

COOL VPN Down went down at 11:00AM on Jan 7, 2021.

**Comment by jsf9k** [comment]
The VPN is back up now.  More to follow.

**Comment by jsf9k** [comment]
I was upgrading the FreeIPA cluster when this happened.  I was in the process of upgrading `ipa1` at the time and was just beginning [this step](https://github.com/cisagov/cool-system/wiki/Upgrading-the-FreeIPA-cluster#recreate-ipa1-and-add-it-back-into-the-freeipa-cluster) when @brubach told me that the VPN was down.  I believe what happened is that I changed the FreeIPA DNS records to advertise `ipa0` instead of `ipa1`, but due to the large TTL value the VPN server did not refresh its DNS cache.  Hence, when I terminated the `ipa1` the VPN server was still trying to communicate with it.

A way to avoid this in the future is to change the FreeIPA TTLs to a low value at least 24 hours before we intend to perform an upgrade.  This way we will know that the OpenVPN server is using the new TTL.  Then we can perform the upgrade process and finally revert the TTL to its default value of `86400`.

I'm curious to know what @dav3r thinks of this plan.

**Comment by dav3r** [comment]
> I'm curious to know what @dav3r thinks of this plan.

While I don't love the idea of having to change the IPA TTLs a day in advance, I can't think of a better way to accomplish this. 
 I'm good with making this change to our runbook, at least until we come up with a superior solution.

**Comment by jsf9k** [comment]
We could alternatively change the long-term TTL to something like `3600`.  Then we would only need to reduce it to a very low value an hour or so before updating.  This wouldn't vastly increase DNS traffic, and would make the update process a single day affair.

**Comment by dav3r** [comment]
That is definitely preferable- we will have to remember to add a good comment explaining why the TTL is as low as it is.
