### ISSUE TITLE
Prevent VPN access to metadata service

### ISSUE THREAD

**Issue by felddy** [cisagov/cool-system#175]
# 🐛 Summary #

It is possible for authenticated OpenVPN users to access the metadata service. 

## To reproduce ##

1. Modify OpenVPN configuration to route packets destined to the metadata service to the VPN gateway.
1. Connect to the VPN.
1. Make a request to the metadata service.

## Expected behavior ##

Requests to the metadata service should not receive a response.
Packets should be dropped or rejected.

**Comment by jsf9k** [comment]
I did some testing and verified that implementing the changes in #174 fixes this issue.  The reason is that [the response to a PUT request to retrieve an IMDSv2 token respects the IMDSv2 hop limit value](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html), which [is configurable](https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-metadata-options.html) but defaults to one.  As is stated in the first link, 
> By default, the response to PUT requests has a response hop limit (time to live) of 1 at the IP protocol level.
