### ISSUE TITLE
Grant direct ssh access for a subset of assessors

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-system#179]
# 💡 Summary #

Consider giving direct (i.e., not via Guacamole) ssh access to assessment instances for Fed leads and certain "trusted" contractors.

## Motivation and context ##

@dav3r mentioned that he received a request for this.  @dav3r, can you explain what need this addresses?

## Implementation notes ##

* We would need to create AWS users for these folks and grant them sufficient permissions to ssh via SSM Session Manager.
* Since these instances would already be on the domain, the users could authenticate via their Kerberos credentials.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by dav3r** [comment]
I was referring to the desire mentioned by @justinforbes a while back for assessors to be able to ssh directly to COOL instances that they have been given access to.  I believe this was mainly so that they could use their local terminal configuration, but Justin can clarify if he wants.  

Also, I am not sure what the final verdict was on if this type of access would be allowed by Assessment management.
