### ISSUE TITLE
No more multiple user on Kalis (env6)

### ISSUE THREAD

**Issue by sporac** [cisagov/cool-system#183]
This behavior appears restricted to env6.

Only 1 user can access a Kali at a time. When an additional session is established, the original user to kick off/loses connection to Kali. This appears to be new behavior beginning with env6.

This behavior is not present in the pen-test portals.

**Comment by jsf9k** [comment]
I will be working on this tomorrow.  I suspect it is related to [this change](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md), which has hit Debian 11 (which Kali Linux is currently based on) but has not yet hit Debian 10 (which the pentest portal AMI is based on).

**Comment by jsf9k** [comment]
[These instructions](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md) indicate that we need to change the way our VNC server is deployed, so I made those changes manually in a COOL staging environment.  (The new way is simpler, so I'm happy to use it.)  The changes were successful in that the VNC server is running on Kali, but connections are still not shared - even with `~/.vnc/config` configured like this:
```config
root@kali:/var/log# less ~vnc/.vnc/config 
allowoverride=alwaysshared
alwaysshared
disconnectclients=no
geometry=1920x1080
localhost=no
log=*:syslog:100
nevershared=0
securitytypes=vncauth
session=xfce
```

After a lot of head scratching and Googling, I stumbled on TigerVNC/tigervnc#1097 and TigerVNC/tigervnc#1098.  The bug mentioned in those issues is causing our attempts to modify VNC server settings to allow sharing of connections to fail.  This bug was fixed in [TigerVNC/tigervnc](https://github.com/TigerVNC/tigervnc) months ago, but they haven't released a new version.

Here are my TODOs:
- [ ] Check if there is an existing Debian Bullseye bug for this, and create one if there isn't.  Debian should be able to add a patch for v1.11.0 and release a new TigerVNC system package, which should then flow down to Kali.
- [ ] Also look into forcing Kali to install version 1.10 of TigerVNC as a temporary workaround until an updated system package for v1.11 is released.
- [ ] Verify that the changes mentioned [here](https://github.com/TigerVNC/tigervnc/blob/master/unix/vncserver/HOWTO.md) also work in v1.10.0.  If they do then I'll go ahead and make those changes in [cisagov/ansible-role-vnc-server](https://github.com/cisagov/ansible-role-vnc-server) since this is an improved way of deploying TigerVNC.

**Comment by jsf9k** [comment]
I verified that the package being installed in Kali comes directly from Debian Bullseye with no Kali-specific alterations.  I will spin up a Debian Bullseye Docker container and submit a bug using Debian's `reportbug` tool.

**Comment by jsf9k** [comment]
Debian [has accepted the patch I submitted with the bug I created](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985614#8), and my understanding is that a new version of `tigervnc-standalone-server` should be released soon. :tada:

**Comment by jsf9k** [comment]
The new version of the `tigervnc-standalone-server` Debian package has hit unstable, but [it looks like it will be at least 20 days before it hits testing](https://tracker.debian.org/pkg/tigervnc) (on which Kali Linux is based).  In the meantime, I'll create a PR for [cisagov/ansible-role-vnc-server](https://github.com/cisagov/ansible-role-vnc-server) to pin this package to v1.10 for Kali.
