### ISSUE TITLE
Create cool-ses-send-email-iam repository

### ISSUE THREAD

**Issue by dav3r** [cisagov/cool-system#195]
# 💡 Summary #

Create the `cool-ses-send-email-iam` repository to create all of the Terraform needed for users to assume the [SesSendEmail-cyber.dhs.gov role](https://github.com/cisagov/cool-dns-cyber.dhs.gov/blob/develop/sessendemail_role.tf).

## Motivation and context ##

There are some users who require the ability to assume our [SesSendEmail-cyber.dhs.gov role](https://github.com/cisagov/cool-dns-cyber.dhs.gov/blob/develop/sessendemail_role.tf).

## Implementation notes ##

After this is done, don't forget to delete the temporary group (`TEMP_SES_cyber.dhs.gov_emailers`) and policy (`TEMP-DNS-AssumeSesSendEmail-cyber.dhs.gov`) that was created manually in the Users account.

## Acceptance criteria ##

- [x] Group and policy are successfully created
- [x] Correct users are added to the group
- [x] Temporary group `TEMP_SES_cyber.dhs.gov_emailers` has been deleted
- [x] Temporary policy `TEMP-DNS-AssumeSesSendEmail-cyber.dhs.gov` has been deleted

**Comment by jsf9k** [comment]
Please note the changes I am making in cisagov/cool-dns-cyber.dhs.gov#46.  You will also want to grant these folks access to the suppression list management role so that they can remove folks from that list as necessary.  You may also want to point them to [these instructions](../wiki/Removing-an-Email-Address-from-the-AWS-SES-Suppression-List).
