### ISSUE TITLE
Allow inbound tcp/8000-8999. 

### ISSUE THREAD

**Issue by felddy** [cisagov/cool-system#27]
For the RPT environment, aside from the permitted open ports specified in the UAT plan, please also allow inbound tcp/8000-8999. (I'll update the document.)

_Originally posted by @sporac in https://github.com/cisagov/cool-system/issues/6#issuecomment-613585528_

**Comment by sporac** [comment]
I tested this yesterday, 4 May. It appears that all, but the original 80,443, and 8080 ports are still being blocked.

**Comment by jsf9k** [comment]
I created cisagov/kali-packer#24 and cisagov/teamserver-packer#2 to address the non-Terraform portion of this issue.

**Comment by dav3r** [comment]
I'm reopening this issue because there is still a bit more work to do.

I have applied the Terraform changes to the network ACL and security group rules so that TCP ports 8000-8999 are allowed in to the Operations subnet where the Kali and Teamserver instances reside.

However, we still have to redeploy new Kali and Packer AMIs if we want those ports to be allowed through the UFW on those instances.

**Comment by dav3r** [comment]
Just to document this somewhere, I excluded the default Nessus port (8834) from the requested range of ports in https://github.com/cisagov/cool-assessment-tfvars/commit/11320beac3c94b7682283a8484e622716dc168cc.

**Comment by sporac** [comment]
I will confirm, but the last time I tested this, I was able to access the nessus scanner from my Mac (VPNed into the Cal).

**Comment by jsf9k** [comment]
@sporac, have you been able to confirm that this issue is resolved (or not)?

**Comment by jsf9k** [comment]
@dav3r and I believe that this issue was resolved quite some time ago.  @sporac, please reopen the issue and add a comment if you disagree.
