### ISSUE TITLE
Unique instance/image for Pentest Portal

### ISSUE THREAD

**Issue by KyleEvers** [cisagov/cool-system#83]
# 🚀 Feature Proposal

The Pentest Portal should receive its own instance/security groups and not be built on the TeamServer instance.

## Motivation

The TeamServer requires ports/services to be accessible to the Internet in order to receive beacon callbacks. On the contrary, the Pentest Portals should only be accessible on port 443 to the internal Kali instances.

**Comment by dav3r** [comment]
I'm in the process of building out a new, more generic AMI that can be used to run Pentest Portal:  https://github.com/cisagov/docker-packer

When it's done, I will also need to make updates to https://github.com/cisagov/cool-assessment-terraform so that we can deploy instances based on [`docker-packer`](https://github.com/cisagov/docker-packer) to assessment environments.

**Comment by dav3r** [comment]
@KyleEvers - After https://github.com/cisagov/cool-assessment-terraform/pull/67 is merged, I will be able to modify your environment to reduce the number of Teamservers and replace them with the new Pentest Portal instances.
